// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRnBp-w6VxiJK3pr5UDC4_mrMUgsa_XDM',
    appId: '1:64783257839:web:323c60f1836d3534eb0b1a',
    messagingSenderId: '64783257839',
    projectId: 'test-login-7fcca',
    authDomain: 'test-login-7fcca.firebaseapp.com',
    storageBucket: 'test-login-7fcca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr98oxeCARMplphwiz4l7nISXRPKiFO00',
    appId: '1:64783257839:android:503637065b051232eb0b1a',
    messagingSenderId: '64783257839',
    projectId: 'test-login-7fcca',
    storageBucket: 'test-login-7fcca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCGvC9LnZQBSSy6gGVHfoZEfSjm-paoss',
    appId: '1:64783257839:ios:0fa061ee818d3667eb0b1a',
    messagingSenderId: '64783257839',
    projectId: 'test-login-7fcca',
    storageBucket: 'test-login-7fcca.firebasestorage.app',
    iosBundleId: 'com.example.actividadNotificaciones',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCGvC9LnZQBSSy6gGVHfoZEfSjm-paoss',
    appId: '1:64783257839:ios:0fa061ee818d3667eb0b1a',
    messagingSenderId: '64783257839',
    projectId: 'test-login-7fcca',
    storageBucket: 'test-login-7fcca.firebasestorage.app',
    iosBundleId: 'com.example.actividadNotificaciones',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRnBp-w6VxiJK3pr5UDC4_mrMUgsa_XDM',
    appId: '1:64783257839:web:1b938529b61dad43eb0b1a',
    messagingSenderId: '64783257839',
    projectId: 'test-login-7fcca',
    authDomain: 'test-login-7fcca.firebaseapp.com',
    storageBucket: 'test-login-7fcca.firebasestorage.app',
  );
}
